import NavBarr from './(Components)/(NavBar)/NavBarr'
import './globals.css'
import { Inter } from 'next/font/google'
import { ContextProvider } from './(Components)/(Context)/ContextProvider'
import Apicontextprovider from './(Components)/(Apicontext)/Apicontextprovider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <Apicontextprovider>
        <div style={{width:'100%', overflow:'hidden',position:'fixed', top:'0',}}>
          <NavBarr children={children}/>
        </div>
        </Apicontextprovider>
        </ContextProvider>
      </body>
    </html>
  )
}
